name: Test

on:
  push:
    branches:
     - main

jobs:
  test-unit:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Setup php 8.1
    #  run:  sudo update-alternatives --set php /usr/bin/php && php -v

    - name: Validate composer.json and composer.lock
      run:  composer validate

    - name: Install dependencies
      run:  composer install --no-progress --no-suggest

    - name: Run test suite
      run:  composer run coverage
